package frame;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import util.SwingUtil;

import javax.swing.*;
import java.awt.*;

/**
 * <h1>注册成功对话框类</h1>
 *
 * <p>通过 Idea 的 GUI Designer 插件生成布局代码</p>
 * <p>使用了 Idea 的第三方库</p>
 *
 * @author: wjl
 * @date: 2022/1/8 18:57
 * @version: v1.0
 */
public class RegisterDialog extends JDialog {

    private JPanel pane;               // 主面板
    private JPanel messagePane;        // 消息面板
    private JPanel buttonPane;         // 按钮面板
    private JButton buttonOK;          // 确认按钮

    public RegisterDialog() {
        // generated by GUI designer
        pane = new JPanel();
        pane.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        pane.setPreferredSize(new Dimension(250, 150));
        buttonPane = new JPanel();
        buttonPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pane.add(buttonPane, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        buttonOK = new JButton();
        buttonOK.setText("确定");
        buttonPane.add(buttonOK, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(70, 30), null, 0, false));
        messagePane = new JPanel();
        messagePane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pane.add(messagePane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = SwingUtil.getFont(null, -1, 20, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("注册成功");
        messagePane.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

        // 初始化容器参数
        setContentPane(pane);
        setModal(true);
        getRootPane().setDefaultButton(buttonOK);
        buttonOK.addActionListener(e -> onOK());
    }

    private void onOK() {
        dispose();
    }

    public JPanel getPane() {
        return pane;
    }

    public void setPane(JPanel pane) {
        this.pane = pane;
    }

}
